version: 0.0
os: windows
files:
  - source: /deploy/
    destination: C:\Apache24\htdocs
hooks:
  BeforeInstall:
    - location: scripts\start_server.ps1
      timeout: 900
      runas: Administrator
